spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sales
    username: sales
    password: sales
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
